### ISSUE TITLE
Where is the invocations_per_hour_atc.tsv?

### ISSUE THREAD

**Issue by huangyz0918** [Azure/AzurePublicDataset#10]
Hello, I saw some dataset introduced in the [notebook](https://github.com/Azure/AzurePublicDataset/blob/master/analysis/AzureFunctionsDataset2019-Trace_Analysis.md) but cannot find them in the dataset downloaded. Should we process and generate by ourselves or can you share the generating scripts for them?

For example, I cannot find what `invocations_per_hour_atc.tsv` in this repo, which you have mentioned in the notebook.

**Comment by rfonseca** [comment]
Hi @huangyz0918,
The _atc datasets are not released. You cannot run the notebook as is with the data in the public release, you can only reproduce, with some pre-processing of the data, the curves labeled 'Released'. The goal of the notebook is to show that the curves that you can reproduce from the released data are close to the ones we produced with the larger dataset for the paper.
Thanks for the interest in the data!
