### ISSUE TITLE
Negative average execution time in function_durations_percentiles.anon.d01.csv

### ISSUE THREAD

**Issue by CodingYuanLiu** [Azure/AzurePublicDataset#13]
Hello everyone,
I've found 5 negative values of `Average` field in **function_durations_percentiles.anon.d01.csv**
For example, in line 35816, the `Average` is -41692
As the `Average` field indicates average execution time (ms) across all invocations of the 24-period, how can this value be negative?
Thank you very much in advance

**Comment by rfonseca** [comment]
Hi @CodingYuanLiu, thank your for pointing this out. Unfortunately, this is a glitch in the data collection, and we can't fix these, as the non-aggregated execution data has not been saved. In these cases, you might consider looking at the CDF sketch (the percentiles in the data), and either estimate the mean from the percentiles, or use the median, which should be more robust to glitches.
