### ISSUE TITLE
AzureTracesForPacking2020 - VM Create Times?

### ISSUE THREAD

**Issue by smiqbal** [Azure/AzurePublicDataset#14]
In the AzureTracesForPacking2020 dataset, there are 3414 rows with a starttime of -7157. That would mean these VMs have existed for almost 20 years before the trace logging began. This may just be a logging error/artifact but I wanted to confirm.

**Comment by mathgeekcoder** [comment]
Thanks for noticing this issue! 

Indeed this was my mistake, and caused by missing data.  We will update the dataset, but in the meantime you can replace the -7157 entries with -1497 (~4 years).

**Comment by smiqbal** [comment]
Thank you for the quick response!
