### ISSUE TITLE
Is there a function call chain in AzureFunctionDataset2019?

### ISSUE THREAD

**Issue by GitHubDiom** [Azure/AzurePublicDataset#16]
The CSV files `invocations_per_function*` provide the function trigger as `HTTP`, `Queue` or othes.

Are these functions are triggered by another function? like, function A triggers function B over the HTTP protocol. If so, could this trace provide such a function call chain?

Thanks

**Comment by rfonseca** [comment]
A function can trigger another function directly (e.g., HTTP call, or via Durable Functions - activities are triggered by coordinators, for example), or indirectly (a function can be triggered by queue items, or by items stored in blob storage, for example). Unfortunately the log does not capture the relationship between different functions. You may try to infer some relationship by finding correlations in the per-minute invocation counts of two or more functions. In the future we may be able to release a trace of chained invocations, but this is not in this trace.
Thanks for the interest in the workload!
