### ISSUE TITLE
Trace start weekday

### ISSUE THREAD

**Issue by Francis-Liu** [Azure/AzurePublicDataset#2]
One frustrating thing about the trace is that the start weekday and time are unknown. E.g., does time 0 start at 00:00 AM on a Sunday or Monday?

**Comment by knodir** [comment]
Isn't the start day Wednesday, November 16, 2016? I.e., 00:01 would refer to the first minute of the Wednesday? My understanding is based on the Section 3 of the Resource Central [paper](https://dl.acm.org/citation.cfm?id=3132772), which says following:

> Dataset. Our dataset contains information about every VM running on Azure from November 16, 2016 to February 16, 2017.

So, in my use of dataset, I am assuming the start time to be Wednesday. Note that I am not affiliated with the team, just using the dataset for my research.

**Comment by elicortez** [comment]
Actually, we (on purpose) do not provide the exact date of the trace for Data anonymization sack.
