### ISSUE TITLE
Fail to download Azure Functions Invocation Trace 2021

### ISSUE THREAD

**Issue by jiachengcai** [Azure/AzurePublicDataset#24]
I can't fetch https://[raw.githubusercontent.com](https://raw.githubusercontent.com/Azure/AzurePublicDataset/master/data/AzureFunctionsInvocationTraceForTwoWeeksJan2021.rar)/Azure/AzurePublicDataset/master/data/AzureFunctionsInvocationTraceForTwoWeeksJan2021.rar 
How can i download this dataset

**Comment by rfonseca** [comment]
The link is working now.
