### ISSUE TITLE
Duration of Azure Functions Invocation Trace 2021

### ISSUE THREAD

**Issue by GitHubDiom** [Azure/AzurePublicDataset#25]
Thank you for releasing the trace.

I have conducted a simple analysis of the trace, and I found the `duration` in the trace fluctuated considerably. 

Does the `duration` in Azure Functions Invocation Trace 2021 include the cold start time?

Or maybe it just has to do with the user invoking the function parameters or the network?

Thank you.

**Comment by BEbillionaireUSD** [comment]
I guess it doesn't contain the cold start time, but I have the same question.

**Comment by hyzheng-1** [comment]
same question.
maybe under different workload?

**Comment by rfonseca** [comment]
The duration field does not include the cold start time, it is the time the function invocation took to execute. We didn't track the reason for the variation. It could include part of the cold start (it there is some JIT being done, for example, for the first invocation), but not the time to create sandboxes, schedule, etc. It could also vary depending on input, and even on interference with other concurrent executions in the same node.
