### ISSUE TITLE
Clarification on simulated 336k VM arrivals

### ISSUE THREAD

**Issue by knodir** [Azure/AzurePublicDataset#3]
I find inconsistency between numbers reported on the [paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/10/Resource-Central-SOSP17.pdf) and an actual dataset. Can someone please clarify which source is true?

Section 6.2 of the paper says 
> [...] we simulate 336k VM arrivals to a cluster of 880 servers (each with 16 cores and 112 GBytes of RAM) over a period of 1 month.

I assume this is describing [vmtable.csv](http://azurepublicdataset.blob.core.windows.net/azurepublicdataset/trace_data/vmtable/vmtable.csv.gz) which actually has VM arrivals for 30 days. However, the number of those arrivals are over 2 million (2,013,767 to be precise), which is equal to the number of lines in the csv file. I confirmed every line to correspond to the new VM arrival (no duplicates). So, does the `simulated 336k` arrivals refer to the subset of the vmtable.csv? If yes, can it be a random subset, top 336k lines, or something else? Or, perhaps, the paper has a typo where authors actually intended to write `over 2 million` instead of 336k?

Any hint is appreciated.

**Comment by elicortez** [comment]
Hi, Thanks for reaching out.
The sample used in the simulation is part of the dataset. As pointed out in the paper, the set of VMs in the simulation has similar characteristics to the dataset and to the VM workload analysis presented in the resource central paper.
