### ISSUE TITLE
Azure Functions Trace 2019 link not working

### ISSUE THREAD

**Issue by cvetkovic** [Azure/AzurePublicDataset#35]
Hi. I noticed that the Azure Functions 2019 trace does not work anymore.

![image](https://github.com/Azure/AzurePublicDataset/assets/16463659/dac58d10-1d98-41b4-a629-c967a5940cb9)

https://azurecloudpublicdataset2.blob.core.windows.net/azurepublicdatasetv2/azurefunctions_dataset2019/azurefunctions-dataset2019.tar.xz

**Comment by rfonseca** [comment]
Hi Lazar, 

We had to change the link, the new link in the page should work now.

Thanks!
Rodrigo

**Comment by liangcheng-yu** [comment]
Hi Rodrigo,

Tried using the new link: https://azurecloudpublicdataset2.z19.web.core.windows.net/azurepublicdatasetv2/azurefunctions_dataset2019/azurefunctions-dataset2019.tar.xz  in the page https://github.com/Azure/AzurePublicDataset/blob/master/AzureFunctionsDataset2019.md, yet the link seems invalid.

Looking forward to the advice. Thanks!

**Comment by natmarbal** [comment]
@rfonseca the new link for the traces in `AzureFunctionsDataset2019.md` doesn't work. When clicking on the link, one gets the following error message:
```
The requested content does not exist.
HttpStatusCode: 404
ErrorCode: WebContentNotFound
RequestId : 9c48faed-c01e-0000-641c-c44d94000000
TimeStamp : 2024-06-21T20:49:29.4181561Z
```

**Comment by liangcheng-yu** [comment]
Related, links in https://github.com/Azure/AzurePublicDataset/blob/master/AzurePublicDatasetV1Links.txt and https://github.com/Azure/AzurePublicDataset/blob/master/AzurePublicDatasetLinksV2.txt are also no longer accessible. Thanks!

**Comment by liangcheng-yu** [comment]
Perhaps related: Other links, e.g., those in https://github.com/Azure/AzurePublicDataset/blob/master/AzurePublicDatasetLinksV2.txt are also inaccessible. Thanks!
