### ISSUE TITLE
How do we identify the number of cores on each of the VMs in the DatasetV2?

### ISSUE THREAD

**Issue by mustafaquraish** [Azure/AzurePublicDataset#5]
We're currently using the v1 dataset as part of our research, and we would like to use the v2 as well since it has more - and up to date - data. However, I'm not sure if we're misunderstanding the dataset, but we cannot find a way to identify the core count of the VMs, we only see the bucket they belong to.

We need this information to do our research, so could you help me in figuring out how to get this information from the dataset? Or is it the case that it isn't meant to be available? If so, do you plan on releasing this information on a later date?

**Comment by elicortez** [comment]
HI,

For the DatasetV2 we do not plan to share the exact number of cores and amount of memory per VM.
