### ISSUE TITLE
Does VM create timestamp correspond to request arrival time?

### ISSUE THREAD

**Issue by knodir** [Azure/AzurePublicDataset#6]
Hello,

I am using V1 dataset for my research where I assume VM create times in `vmtable.csv` correspond to the VM request arrival time. Is this a valid assumption? Note that `VM create` time refers to the time when cloud scheduler created the VM while `request arrival` refer to the time when customer requested to create a VM.

For example, for the case below, can I assume that `vm1` create request arrived before `vm2`?
```
vm1,0,900
vm2,300,900
```

My example simplifies the data format `vmtable.csv` as `vm_uuid, create_time, delete_time`.

Thanks!

**Comment by elicortez** [comment]
Hi,

Thanks for reaching out. You are right in the sense that "vm created time" and "customer request time" carry different semantics, however in the traces we provide we do not differentiate them. 
In this context and according to your example, it's save to assume vm1 was requested before vm2.

Best,
