### ISSUE TITLE
Does VM order in vmtable.csv signify VM creation order?

### ISSUE THREAD

**Issue by knodir** [Azure/AzurePublicDataset#7]
This is somehow relevant to issue #6 but this is about VMs that have the same create timestamp (instead of different timestamps in issue #6).

The paper says that the VM data is captured every 5 mins, i.e., VM creates happen with 300 seconds interval. Is it fair to use the line numbers in `vmtable.csv` to signify the order VMs created? I.e., lower line number (appears earlier in the `.csv` file) means VM was created before the later VMs.

For example, in this simplifies the data format from `vmtable.csv` as `vm_uuid, create_time, delete_time`, can I assume `vm2` was created after `vm1`?

```
vm1,0,900
vm2,0,600
vm3,300,900
vm4,0,900
```

Note that this is a question about V1 dataset, although could be applicable to V2 as well. 

Thanks!

**Comment by elicortez** [comment]
Hi,

You can make this assumption, but you can also assume that they were requested/created at the same time.

**Comment by knodir** [comment]
Thanks for the quick answer!

**Comment by knodir** [comment]
Re-opening this issue to clarify the order in presence of `deployment IDs`. In the example below, can we swap `vm4` with `vm3` so that VM create requests in deployment appear next to each other?

Original
```
vm1,dep1,0,900
vm2,dep1,0,600
vm3,dep2,0,900
vm4,dep1,0,900
```

Swapped
```
vm1,dep1,0,900
vm2,dep1,0,600
vm4,dep1,0,900
vm3,dep2,0,900
```

Thanks!

**Comment by elicortez** [comment]
Yes, that's totally fine.
