### ISSUE TITLE
Early Access for Azure Functions Traces

### ISSUE THREAD

**Issue by nimamahmoudi** [Azure/AzurePublicDataset#8]
Hi,

Is there any way we could get early access to the Azure Function Traces for research? BTW, I am a PhD student at the University of Alberta.

Best,
Nima

**Comment by chen0031** [comment]
We still need such data to conduct FaaS experiments.

**Comment by rfonseca** [comment]
The traces are now generally available. Sorry we couldn't make them available earlier.
