### ISSUE TITLE
Azure Functions Dataset 2019 download link not working

### ISSUE THREAD

**Issue by ansjin** [Azure/AzurePublicDataset#9]
Hello,

Thank you for sharing the data however, the link for downloading it is not working. 

https://azurecloudpublicdataset2.blob.core.windows.net/azurepublicdatasetv2/azurefunctions_dataset2019/azurefunctions-dataset2019.tar.xz

![image](https://user-images.githubusercontent.com/10348337/85187328-192ac900-b29f-11ea-923a-d56a20100f51.png)

Update:

However, the individual file link works: https://azurecloudpublicdataset2.blob.core.windows.net/azurepublicdatasetv2/azurefunctions_dataset2019/invocations_per_function_md.anon.d01.csv

**Comment by yuxiaoba** [comment]
It seems that the file type tar.xz has some errors. But replacing it with  tar.gz does not work.

**Comment by rfonseca** [comment]
Thank you. There was a problem uploading the archive, but it is fixed now. There is no .gz, xz compresses the file significantly better than either gz or bzip2.
